id: P057287E7
initial_creation_type: input
source_metadata:
  title: Sixteen Arhats
  language: de
  description: 'A selection of texts related to the Sixteen Arhats or Sixteen Elders
    (ṣoḍaśa sthavirāḥ; Tib. gnas brtan bcu drug):'
  volume:
    f73daa69d2cb433cb0d91328eae160be:
      title: A Brief Practice of Paying Homage and Making Offerings to the Sixteen
        Elders
      parent: Practices
    2abdf94bb8334f9db4950838868296e8:
      title: 'The Heart of Wish-Fulfilling Jewels: A Brief Practice for Paying Homage
        and Making Offerings to the Buddha together with his retinue of Arhats'
      parent: Practices
    526d15eb680c4e82a4471ae8df775586:
      title: A Practice of Paying Homage and Making Offerings to the Sixteen Elders
      parent: Practices
    76a57cc860fb4f3aa5773b9304416894:
      title: A Brief Practice for Paying Homage and Making Offerings to the Buddha
        together with his retinue of Arhats
      parent: Practices
    54b78065796c4f6cab6e723199214da3:
      title: Supplication to Lord Buddha together with the Sixteen Arhats
      parent: Prayers
created_at: '2022-03-01T05:51:16.714493'
last_modified_at: '2022-03-01T05:51:16.714496'
